package/grpc: bump to version 1.25.0
Other changes:

 - Remove upstream patch 0004-Fix-gettid-naming-conflict.patch
 - Remove upstream patch 0005-Rename-gettid-functions.patch
 - Add a check for BR2_TOOLCHAIN_GCC_AT_LEAST_5 in grpc.mk. If the
   selected toolchain is not at least version 5 or higher and the
   optimization level is -Os, set the GRPC_CFLAGS and GRPC_CXXFLAGS
   optimizations to -O2. This check prevents the following error:

   error: failure memory model cannot be stronger than success memory model for '__atomic_compare_exchange'

Tested with test-pkg, all tests passed:
            br-arm-full [1/6]: OK
 br-arm-cortex-a9-glibc [2/6]: OK
  br-arm-cortex-m4-full [3/6]: SKIPPED
         br-x86-64-musl [4/6]: OK
     br-arm-full-static [5/6]: SKIPPED

Signed-off-by: Adam Duskett <Aduskett@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>