package/fxload: re-enable package on microblaze
Building fxload on Microblaze with gcc < 8.x and optimization enabled
fails with:

  Error: operation combines symbols in different segments

This is due to gcc bug 63261
(https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63261).

To work around this, the fxload package has a !BR2_microblaze
dependency. However, gcc bug 63261 only triggers when optimization is
enabled, so a better work around is to pass -O0, which is what we do
in other Buildroot packages to work around this bug.

So, this commit passes -O0 when BR2_TOOLCHAIN_HAS_GCC_BUG_63261, and
re-enables fxload on Microblaze.

Signed-off-by: Giulio Benetti <giulio.benetti@micronovasrl.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>