libglib2: add upstream patch to fix build issue
Since the bump of libglib2 to 2.56.0, it fails to build on uClibc with:

gthreadedresolver.c: In function 'do_lookup_records':
gthreadedresolver.c:875:16: error: 'res' undeclared (first use in this function); did you mean '_res'?
   res_nclose (&res);
                ^~~
                _res

This commit adds an upstream patch that fixes this problem.

Fixes:

  http://autobuild.buildroot.net/results/990e19e3500986263f99354215e33214a2e89116/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>