package/flac: fix powerpc compile failure (missing sys/auxv.h)
Fixes [1]:

  cpu.c:57:10: fatal error: sys/auxv.h: No such file or directory

>From build/flac-1.3.3/src/libFLAC/cpu.c:

  56 #if defined FLAC__CPU_PPC
  57 #include <sys/auxv.h>
  58 #endif

Fixed by configure.ac patch checking for for sys/auxv.h before defining
FLAC__CPU_PPC (fallback already implemented for ppc_cpu_info method in
case FLAC__CPU_PPC is not defined).

[1] http://autobuild.buildroot.net/results/eb3a59a78dbb0c83cff78aac2384edea890af830

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>