Revert "libcrossguid: bump to version 0.2.2"
This reverts commit 89d77e2499b30daf5529244c62cd6f1c81e3a5e6.

Building the only package depending on libcrossguid, Kodi, breaks due to
this bump:

/home/buildroot/br4/output/build/kodi-17.6-Krypton/xbmc/utils/
StringUtils.cpp: In static member function ‘static std::__cxx11::string
StringUtils::CreateUUID()’:
/home/buildroot/br4/output/build/kodi-17.6-Krypton/xbmc/utils/
StringUtils.cpp:1194:10: error: ‘GuidGenerator’ does not name a type
   static GuidGenerator guidGenerator;
          ^~~~~~~~~~~~~
/home/buildroot/br4/output/build/kodi-17.6-Krypton/xbmc/utils/
StringUtils.cpp:1195:15: error: ‘guidGenerator’ was not declared in this
scope
   auto guid = guidGenerator.newGuid();
               ^~~~~~~~~~~~~

This happens due to changes in libcrossguid:
https://github.com/graeme-hill/crossguid/blob/master/README.md

"This is version 0.2 of CrossGuid. If you all already using CrossGuid and
your code uses GuidGenerator then you are using version 0.1."

Even Kodi master branch has no support for libcrossguid-0.2.x yet so we
revert the bump.

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>