libv4l: bump version to 1.16.2
- changes since 1.16.1
  0f68a3f6 configure: build without BPF support in ir-keytable
  5f8bd4e8 keytable: fix compilation warning
  f735bee7 keytable: fix BPF protocol compilation on mips
  c393c3bc Prepare for 1.16.2 release

- use new '--disable-bpf' option instead of ac_cv_prog_CLANG
  to disable BPF support, fixes [1]:

  bpf.c:48:4: error: #error __NR_bpf not defined. libbpf does not support your arch.

- remove upstream denied patch (see [2]) fixing part of the BPF support
  for older toolchains

[1] http://autobuild.buildroot.net/results/32b8f63e84616f91b645230e889eb1518972a398
[2] https://www.spinics.net/lists/linux-media/msg142729.html

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>