package/qt5/qt5base: fix icu detection in Qt 5.6.3
icu is required to build Q5tWebkit.
When UChar is defined as char16_t in ICU, then qtbase fails to detect ICU.
The issue is described https://bugreports.qt.io/browse/QTBUG-49586

Build fails with following error messages:
...
ustring.h:473:20: error: ‘UChar’ does not name a type
 u_strCompare(const UChar *s1, int32_t length1,
                    ^
          ^
make[2]: *** [Makefile:195: icu.o] Error 1
ICU disabled.
The ICU library support cannot be enabled.

Signed-off-by: Andrey Skvortsov <andrej.skvortzov@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>