open-lldp: requires dynamic linking interface (dlopen, ...)
Fixes:
http://autobuild.buildroot.net/results/516456c8e21759e1ecee4ef9f9689a8f720ecd90/

This patch is to fix the following build error:
weak_readline.c:30:19: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
                   ^
compilation terminated.
Makefile:890: recipe for target 'weak_readline.o' failed

Signed-off-by: Laurent Charpentier <laurent_pubs@yahoo.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>