Revert "package/dtc: bump to v1.5.1"
This reverts commit 03e6bacf0f66817f7a0091c6287be679a6c81f48.

This bump breaks the build of a number of defconfigs with errors like:

HOSTCC  scripts/dtc/libfdt/fdt_ro.o
scripts/dtc/libfdt/fdt_ro.c:92:10: error: redefinition of ‘fdt_get_max_phandle’
uint32_t fdt_get_max_phandle(const void *fdt)
^~~~~~~~~~~~~~~~~~~
In file included from scripts/dtc/libfdt/fdt_ro.c:54:
/work/beaglebone/host/include/libfdt.h:384:24: note: previous definition of ‘fdt_get_max_phandle’ was here

So revert it for 2019.11.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>