modem-manager: disable -Werror
Fixes:
http://autobuild.buildroot.net/results/5d9/5d9e299ff12726d07e8a584a213c1d2a2e419594/

The modem-manager build generates a number of build warnings like:

mm-base-manager.c: In function 'handle_set_logging':
mm-base-manager.c:680:15: error: assignment from incompatible pointer type [-Werror]
     ctx->self = g_object_ref (manager);

Which cause a build failure because of -Werror.  Pass
--disable-more-warnings to disable -Werror.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>