package/supertux: fix debug build on uclibc/musl
Always set CMAKE_BUILD_TYPE to Release otherwise supertux will be built
with -pg since:
https://github.com/SuperTux/supertux/commit/afd5f1b33c110104a7f286d6d7854157919a0a52

This will result in the following build failure on uclibc or musl:
[ 77%] Linking C executable sq_static
CMakeFiles/sq_static.dir/sq.c.o: In function `quit':
/home/buildroot/autobuild/instance-3/output/build/supertux-0.6.0/external/squirrel/sq/sq.c:42: undefined reference to `__gnu_mcount_nc'

Fixes:
 - http://autobuild.buildroot.org/results/b0b2e25af198d01713d1e2bcf38c77ae8ffbd7de

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>