package/polkit: needs C++11
polkit depends on spidermonkey since bump to version 0.116 in commit
d3ef1dea4397c15da005885feda53597aa608cbe however build fails with gcc 5:

/home/naourr/work/instance-0/output-1/host/opt/ext-toolchain/mips-linux-gnu/include/c++/5.3.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
polkitbackendjsauthority.cpp:223:13: warning: G_ADD_PRIVATE
                                                  PolkitBackendJsAuthorityPrivate);
             ^
In file included from /home/naourr/work/instance-0/output-1/host/bin/../mips64el-buildroot-linux-gnu/sysroot/usr/include/mozjs-60/js/RequiredDefines.h:32:0,
                 from <command-line>:0:
/home/naourr/work/instance-0/output-1/host/bin/../mips64el-buildroot-linux-gnu/sysroot/usr/include/mozjs-60/mozilla/Char16.h:136:15: error: 'char16_t' does not name a type
 typedef const char16_t* char16ptr_t;
               ^

Fixes:
 - http://autobuild.buildroot.org/results/a7ea21a8e10f32239ee28f58331899912f232ca2

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>